# 监听端口（注意需要引号）
listen_addr: ":443"

# 可选：启用 Socks5 前置代理
enable_socks5: true
# 可选：配置 Socks5 代理地址
socks_addr: ip:port

# 可选：允许所有域名（会忽略下面的 rules 列表）
#allow_all_hosts: true

# 可选：仅允许指定域名
rules:
  - gstatic.com
  - cloudflare.com